-- ═══════════════════════════════════════════════════════
-- JitHome — Import Patient Data from Google Sheets CSV
-- 30 patients · 202 injection records
-- รัน SQL นี้ใน Supabase SQL Editor
-- ═══════════════════════════════════════════════════════

-- Step 1: เพิ่มผู้ป่วย (ถ้าซ้ำชื่อจะข้ามอัตโนมัติ)
INSERT INTO public.patients (name, village) VALUES
  ('นายอุทัย แสงงาม', 'หมู่ 5'),
  ('นายอุุดร ไชยพันโท', 'หมู่ 9'),
  ('นายสุรชัย พิมพ์สอน', 'หมู่ 6'),
  ('นางไสว ไชยพันโท', 'หมู่ 9'),
  ('นายนันทโก คุณพาที', 'หมู่ 1'),
  ('นายศักดา เรืองสา', 'หมู่ 8'),
  ('นายวีรชัย บัวถา', 'หมู่ 1'),
  ('นายนันทวุฒิ จันทชารี', 'หมู่ 1'),
  ('นายอรรถพงษ์ วงษายะ', 'หมู่ 1'),
  ('นายคำหล้า ขันตะคุต', 'หมู่ 1'),
  ('นายก้องเกียรติ อู่แก้ว', 'หมู่ 3'),
  ('นายสีทา จันทะชารี', 'หมู่ 4'),
  ('นายแพว กุลสิริ', 'หมู่ 4'),
  ('นางโกศรี สีดาแก้ว', 'หมู่ 5'),
  ('นายสิทธิโชค สายใจ', 'หมู่ 5'),
  ('นายอาทิตย์ วงศ์ชาลี', 'หมู่ 7'),
  ('นายสุวัจน์ ศรีประเสริฐ', 'หมู่ 8'),
  ('นายบัวพา สุวรรณรมย์', 'หมู่ 4'),
  ('นางสาวสุดาพร แก้วงาม', 'หมู่ 1'),
  ('นายสมเด็จ ไชยพันโท', 'หมู่ 7'),
  ('นายสีทา จัันทะชารี', 'หมู่ 4'),
  ('นายสิทธิ์โชค สายใจ', 'หมู่ 5'),
  ('นายวิชาญ สีดาแก้ว', 'หมู่ 5'),
  ('พระนันทรักษ์ ศรีวงศ์ษา', 'หมู่ 3'),
  ('นางสาวโกศรี สีดาแก้ว', 'หมู่ 5'),
  ('นางเฟื้องฟ้า อัปกาญจน์', 'หมู่ 6'),
  ('นายโพธิ์ไทร สิงหาปันยา', 'หมู่ 1'),
  ('พระนันทโก คุณพาที', 'หมู่ 1'),
  ('นายอุดร ไชยพันโท', 'หมู่ 9'),
  ('นายประพาพร คำเนตร', 'หมู่ 6')
ON CONFLICT (name) DO NOTHING;

-- Step 2: เพิ่มประวัติการฉีดยา
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-05', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '3 สัปดาห์', 21, '' FROM public.patients WHERE name='นายอุทัย แสงงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-05-15', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายอุุดร ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-11', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-09', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, 'ไม่มา' FROM public.patients WHERE name='นางไสว ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-05-21', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายอุทัย แสงงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-02', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายอุุดร ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-13', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายนันทโก คุณพาที' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-04-14', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, 'ไม่มา' FROM public.patients WHERE name='นายศักดา เรืองสา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-05-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'มา' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2024-11-30', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ไม่ยาฉีด/cosult · อาการปกติ' FROM public.patients WHERE name='นายนันทวุฒิ จันทชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-26', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายอรรถพงษ์ วงษายะ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-05-27', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-05-21', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'มา' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-05-27', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายสีทา จันทะชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-05-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'มา' FROM public.patients WHERE name='นางโกศรี สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-05-11', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ไม่มา' FROM public.patients WHERE name='นายสิทธิโชค สายใจ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-05-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายอาทิตย์ วงศ์ชาลี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-05-07', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, 'ไม่มา' FROM public.patients WHERE name='นายสุวัจน์ ศรีประเสริฐ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-15', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายบัวพา สุวรรณรมย์' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-21', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, 'มา' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-23', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นางสาวสุดาพร แก้วงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-04', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '1 เดือน', 30, 'ฉีดยา  Invega 100 mg inj.' FROM public.patients WHERE name='นายอุุดร ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นางโกศรี สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-26', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายสมเด็จ ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-27', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายสีทา จัันทะชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-12', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '2 สัปดาห์', 14, 'มียา DEPO-A ฉีด ทุก 3 เดือน' FROM public.patients WHERE name='นายสิทธิ์โชค สายใจ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-29', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-25', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, 'เผาเสื้อผ้า ทำลายข้าวของ มียา DEPO-A ฉีด ทุก 3 เดือน' FROM public.patients WHERE name='นายอุทัย แสงงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-06-10', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายศักดา เรืองสา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-04', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, 'ฉีดยา  Invega 100 mg inj. · มียา DEPO-A ฉีด ทุก 3 เดือน' FROM public.patients WHERE name='นายอุุดร ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-04', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, 'ฉีดยา 4 มิ.ย 68' FROM public.patients WHERE name='นายสุวัจน์ ศรีประเสริฐ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-04', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 4 มิ.ย 68' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-08', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, 'ฉีดยา 8 มิ.ย 68 · มียา DEPO-A ฉีด ทุก 3 เดือน' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-10', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 10 มิ.ย 68' FROM public.patients WHERE name='นายศักดา เรืองสา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-28', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายอาทิตย์ วงศ์ชาลี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-15', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 เดือน', 90, 'มียา DEPO-A ฉีด ทุก 3 เดือน' FROM public.patients WHERE name='นายอุุดร ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-13', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 13 มิ.ย 68' FROM public.patients WHERE name='นายนันทโก คุณพาที' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-15', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 15 มิ.ย 68' FROM public.patients WHERE name='นายบัวพา สุวรรณรมย์' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-01', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '2 สัปดาห์', 14, 'ฉีดยา 17 มิ.ย 68' FROM public.patients WHERE name='นายสิทธิ์โชค สายใจ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-21', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-21', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 23 มิ.ย.68' FROM public.patients WHERE name='นางสาวสุดาพร แก้วงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 25 มิ.ย.68' FROM public.patients WHERE name='นางสาวโกศรี สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 25 มิ.ย.68' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-26', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 26 มิ.ย.68' FROM public.patients WHERE name='นายอรรถพงษ์ วงษายะ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-27', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 27 มิ.ย.68' FROM public.patients WHERE name='นายสีทา จันทะชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 27 มิ.ย.68' FROM public.patients WHERE name='นายอาทิตย์ วงศ์ชาลี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-29', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 1 ก.ค.68' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-04', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีีดยา 4 ก.ค.68 · ￼ อาการคุ้มคลั่งตำรวจนำส่งโรงบาลโพธิ์ไทรวันที่ 16 กรกฎา 2568' FROM public.patients WHERE name='นายอุุดร ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-07-25', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, 'ฉีดยา 25 มิ.ย.68' FROM public.patients WHERE name='นายสุวัจน์ ศรีประเสริฐ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 3 ก.ค.68' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-04', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 6 ก.ค.68' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-05', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 8 ก.ค.68' FROM public.patients WHERE name='นายศักดา เรืองสา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-08', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, 'ฉีดยา 8 ก.ค.68 · มียา DEPO-A ฉีด 8 ก.ค.68 ทุก 3 เดือน' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-13', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, 'ฉีดยา 13 ก.ค.68' FROM public.patients WHERE name='นายนันทโก คุณพาที' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-15', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, 'ฉีดยา 13 ก.ค.68' FROM public.patients WHERE name='นายบัวพา สุวรรณรมย์' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-16', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, 'ฉีดยา 19 ก.ค.68' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-23', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 23 ก.ค.68' FROM public.patients WHERE name='นางสาวสุดาพร แก้วงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 25 ก.ค.68' FROM public.patients WHERE name='นางสาวโกศรี สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 25 ก.ค.68' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-26', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 25 ก.ค.68' FROM public.patients WHERE name='นายอรรถพงษ์ วงษายะ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-29', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, 'ฉีดยา 29 ก.ค.68' FROM public.patients WHERE name='นายอาทิตย์ วงศ์ชาลี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-01', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 29 ก.ค.68' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีดยา 29 ก.ค.68' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-04', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, 'ฉีด4สค68' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-13', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, 'ฉีด13สค68' FROM public.patients WHERE name='นายนันทโก คุณพาที' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-14', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, 'ฉีด 14 ส.ค.68 · มา จาก รพ.พระศรี' FROM public.patients WHERE name='นายอุทัย แสงงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 25 ก.ค.68' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-13', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, 'ฉีด13สค68' FROM public.patients WHERE name='นายศักดา เรืองสา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-08', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, 'ฉีด 14 ส.ค.68' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-08-14', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, 'ฉีด 14 ส.ค.68/ DMPA' FROM public.patients WHERE name='นายสิทธิ์โชค สายใจ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-04', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, '' FROM public.patients WHERE name='นายสิทธิ์โชค สายใจ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-04', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, '' FROM public.patients WHERE name='นายอุทัย แสงงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-15', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 15 ส.ค.68' FROM public.patients WHERE name='นายบัวพา สุวรรณรมย์' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-13', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 15 ส.ค.68' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-26', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 26 ส.ค.68' FROM public.patients WHERE name='นายอรรถพงษ์ วงษายะ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 26 ส.ค.68' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 26 ส.ค.68' FROM public.patients WHERE name='นายอาทิตย์ วงศ์ชาลี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-30', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 1 ก.ย.68' FROM public.patients WHERE name='นายสีทา จันทะชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-01', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 1 ก.ย.68' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 3 ก.ย.68' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-03', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, 'ฉีด 3 ก.ย.68' FROM public.patients WHERE name='นายศักดา เรืองสา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 3 ก.ย.68' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-05', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-29', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, 'ฉีด 8 ก.ย.68' FROM public.patients WHERE name='นายอุทัย แสงงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-09-22', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '3 สัปดาห์', 21, 'ฉีด 8 ก.ย.68' FROM public.patients WHERE name='นายสิทธิโชค สายใจ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-11', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 13 ก.ย.68' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-14', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-15', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 15 ก.ย.68' FROM public.patients WHERE name='นายบัวพา สุวรรณรมย์' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 ก.ย.68' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 ก.ย.68' FROM public.patients WHERE name='นางโกศรี สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-25', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '1 เดือน', 30, 'ฉีด 25 ก.ย.68' FROM public.patients WHERE name='นายสุวัจน์ ศรีประเสริฐ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-26', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 27 ก.ย.68' FROM public.patients WHERE name='นายอรรถพงษ์ วงษายะ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 27 ก.ย.68' FROM public.patients WHERE name='นายอาทิตย์ วงศ์ชาลี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-29', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 29 ก.ย.68' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-30', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 30 ก.ย.68' FROM public.patients WHERE name='นายสีทา จันทะชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-21', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, 'ฉีด 30 ก.ย.68' FROM public.patients WHERE name='นายสิทธิโชค สายใจ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-21', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, 'ฉีด 30 ก.ย.68' FROM public.patients WHERE name='นายอุทัย แสงงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-10-29', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 29 ก.ย.68' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-01', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 1 ต.ค.68' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-03', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 3 ต.ค.68' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 3 ต.ค.68' FROM public.patients WHERE name='นางเฟื้องฟ้า อัปกาญจน์' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 3 ต.ค.68' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 3 ต.ค.68' FROM public.patients WHERE name='นายศักดา เรืองสา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-10', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 13 ต.ค.68' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-13', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 13 ต.ค.68' FROM public.patients WHERE name='นายนันทโก คุณพาที' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-19', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '1 เดือน', 30, 'ฉีด 19 ต.ค.68' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-23', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 23 ต.ค.68' FROM public.patients WHERE name='นางสาวสุดาพร แก้วงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-14', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, 'ฉีด 24 ต.ค.68' FROM public.patients WHERE name='นายสิทธิโชค สายใจ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-14', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, 'ฉีด 24 ต.ค.68' FROM public.patients WHERE name='นายอุทัย แสงงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 ต.ค.68' FROM public.patients WHERE name='นายสุวัจน์ ศรีประเสริฐ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-30', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด  30 ต.ค.68' FROM public.patients WHERE name='นายสีทา จันทะชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด  30 ต.ค.68' FROM public.patients WHERE name='นายอาทิตย์ วงศ์ชาลี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-26', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด  31 ต.ค.68' FROM public.patients WHERE name='นายอรรถพงษ์ วงษายะ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-11-29', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-01', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นางเฟื้องฟ้า อัปกาญจน์' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-03', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, '' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-08', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-05', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, '' FROM public.patients WHERE name='นายอุทัย แสงงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-05', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, '' FROM public.patients WHERE name='นายสิทธิโชค สายใจ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-05', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, '' FROM public.patients WHERE name='นายศักดา เรืองสา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-13', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายนันทโก คุณพาที' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-19', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-23', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นางสาวสุดาพร แก้วงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-25', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด25 พย 2568' FROM public.patients WHERE name='นางโกศรี สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-24', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด24 พย 2568' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-26', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายอรรถพงษ์ วงษายะ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-30', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายสีทา จันทะชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-01-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-01-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-01-08', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-27', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, '' FROM public.patients WHERE name='นายอุทัย แสงงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2025-12-27', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '3 สัปดาห์', 21, '' FROM public.patients WHERE name='นายสิทธิโชค สายใจ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-01-01', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-01-13', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายนันทโก คุณพาที' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-01-23', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-01-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, '' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-02-02', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด2มกราคม2569' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-02-04', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด2มกราคม2569' FROM public.patients WHERE name='นายสมเด็จ ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-02-28', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด8มกราคม2569' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-02-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 มกราคม 2569' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-02-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 มกราคม 2569' FROM public.patients WHERE name='นางสาวโกศรี สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-02-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 27 มกราคม 2569' FROM public.patients WHERE name='นายสุวัจน์ ศรีประเสริฐ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-02-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 30 มกราคม 2569' FROM public.patients WHERE name='นายสีทา จันทะชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-02-27', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 30 มกราคม 2569' FROM public.patients WHERE name='นายอรรถพงษ์ วงษายะ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-01', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 2 กุมภาพันธ์ 2569' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 3 กุมภาพันธ์ 2569' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 3 กุมภาพันธ์ 2569' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-02', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'FLUPENTIXOL INJ. 40MG/2ML #1AMP
ฉีด IM 40 MG ทุก 1 เดือน' FROM public.patients WHERE name='นายโพธิ์ไทร สิงหาปันยา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-25', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 25 กุมภาพันธ์ 2569' FROM public.patients WHERE name='นางสาวโกศรี สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 กุมภาพันธ์ 2569' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-23', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 23 กุมภาพันธ์ 2569' FROM public.patients WHERE name='นางสาวสุดาพร แก้วงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-25', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 25 กุมภาพันธ์ 2569' FROM public.patients WHERE name='นายสุวัจน์ ศรีประเสริฐ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-15', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 15 กุมภาพันธ์ 2569' FROM public.patients WHERE name='นายบัวพา สุวรรณรมย์' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-09', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 9 กุมภาพันธ์ 2569' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-25', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 9 กุมภาพันธ์ 2569' FROM public.patients WHERE name='พระนันทโก คุณพาที' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-03', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 2 มีนาคม 2569' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-03', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 2 มีนาคม 2569' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-03', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 2 มีนาคม 2569' FROM public.patients WHERE name='นายอรรถพงษ์ วงษายะ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-03', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 2 มีนาคม 2569' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 4มีนาคม 2569' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-03-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 4มีนาคม 2569' FROM public.patients WHERE name='นายสีทา จันทะชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-08', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 10 มีนาคม 2569' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-19', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 10 มีนาคม 2569' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-20', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 23 มีนาคม 2569' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 มีนาคม 2569' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 มีนาคม 2569' FROM public.patients WHERE name='นางโกศรี สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 มีนาคม 2569' FROM public.patients WHERE name='พระนันทโก คุณพาที' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-25', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 25 มีนาคม 2569' FROM public.patients WHERE name='นายสุวัจน์ ศรีประเสริฐ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-25', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 25 มีนาคม 2569' FROM public.patients WHERE name='นายศักดา เรืองสา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-26', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '1 เดือน', 30, 'ฉีด 25 มีนาคม 2569' FROM public.patients WHERE name='นายอุดร ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 มีนาคม 2569' FROM public.patients WHERE name='นายสีทา จันทะชารี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-04-30', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 2 เมษายน 2569' FROM public.patients WHERE name='นายโพธิ์ไทร สิงหาปันยา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-02', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 2 เมษายน 2569' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 3 เมษายน 2569' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-08', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 3 เมษายน 2569' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-15', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 17 เมษายน 2569' FROM public.patients WHERE name='นายบัวพา สุวรรณรมย์' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-19', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 20 เมษายน 2569' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-18', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 20 เมษายน 2569' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-23', 'green', 'สุขภาพจิต กลุ่ม สีเขียว', '1 เดือน', 30, 'ฉีด 23 เมษายน 2569' FROM public.patients WHERE name='นางสาวสุดาพร แก้วงาม' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 25 เมษายน 2569' FROM public.patients WHERE name='นายวีรชัย บัวถา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-25', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 27 เมษายน 2569' FROM public.patients WHERE name='นางสาวโกศรี สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-28', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 28 เมษายน 2569' FROM public.patients WHERE name='นายอาทิตย์ วงศ์ชาลี' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-05-26', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 1 พฤษภาคม 2569' FROM public.patients WHERE name='พระนันทโก คุณพาที' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 2 พฤษภาคม 2569' FROM public.patients WHERE name='นายแพว กุลสิริ' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-02', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 2 พฤษภาคม 2569' FROM public.patients WHERE name='นายโพธิ์ไทร สิงหาปันยา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-03', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 3 พฤษภาคม 2569' FROM public.patients WHERE name='พระนันทรักษ์ ศรีวงศ์ษา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-02', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '4 สัปดาห์', 28, 'ฉีด 5 พฤษภาคม 2569' FROM public.patients WHERE name='นายศักดา เรืองสา' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-02', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 5 พฤษภาคม 2569' FROM public.patients WHERE name='นายคำหล้า ขันตะคุต' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-06', 'red', 'สุขภาพจิต กลุ่ม สีแดง', '1 เดือน', 30, 'ฉีด 6 พฤษภาคม 2569' FROM public.patients WHERE name='นายอุดร ไชยพันโท' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-09', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 6 พฤษภาคม 2569' FROM public.patients WHERE name='นายประพาพร คำเนตร' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-08', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 10 พฤษภาคม 2569' FROM public.patients WHERE name='นายวิชาญ สีดาแก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-15', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 10 พฤษภาคม 2569' FROM public.patients WHERE name='นายบัวพา สุวรรณรมย์' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-15', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '4 สัปดาห์', 28, 'ฉีด 10 พฤษภาคม 2569' FROM public.patients WHERE name='นายก้องเกียรติ อู่แก้ว' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-19', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 20 พฤษภาคม 2569' FROM public.patients WHERE name='นายสุรชัย พิมพ์สอน' LIMIT 1;
INSERT INTO public.injection_records (patient_id, injection_date, group_color, group_label, interval_str, interval_days, note) SELECT id, '2026-06-23', 'yellow', 'สุขภาพจิต กลุ่ม สีเหลือง', '1 เดือน', 30, 'ฉีด 23 พฤษภาคม 2569' FROM public.patients WHERE name='นางสาวสุดาพร แก้วงาม' LIMIT 1;